config/routes.rb
Rails.application.routes.draw do

  resources :saage_forms
  resources :basic_informations
  resources :bladder_managements
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/my_care_plan' => 'pages#my_care_plan'
  get '/how_to_use' => 'pages#how_to_use'
  get '/about' => 'pages#about'
  
  root 'pages#my_care_plan'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basic_information.rb
class BasicInformation < ApplicationRecord
  belongs_to :saage_form	
end

app/models/bladder_management.rb
class BladderManagement < ApplicationRecord
  belongs_to :saage_form
  enum response: %i[yes no unsure]	
end

app/models/saage_form.rb
class SaageForm < ApplicationRecord
  has_one :basic_information
  has_one :bladder_management
  accepts_nested_attributes_for :basic_information
  accepts_nested_attributes_for :bladder_management  
end

app/models/user.rb
class User < ApplicationRecord
  has_one :saage_form
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/basic_informations_controller.rb
class BasicInformationsController < ApplicationController
  before_action :set_basic_information, only: [:show, :destroy]

  # GET /basic_informations
  # GET /basic_informations.json
  def index
    @basic_informations = BasicInformation.all
  end

  # GET /basic_informations/1
  # GET /basic_informations/1.json
  def show
  end

  # POST /basic_informations
  # POST /basic_informations.json
  def create
    @basic_information = BasicInformation.new(basic_information_params)

    respond_to do |format|
      if @basic_information.save
        format.html { redirect_to @basic_information, notice: 'Basic information was successfully created.' }
      else
        format.html { render :index }
      end
    end
  end

  # PATCH/PUT /basic_informations/1
  # PATCH/PUT /basic_informations/1.json
  def update
  end

  # DELETE /basic_informations/1
  # DELETE /basic_informations/1.json
  def destroy
    @basic_information.destroy
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path, notice: 'Basic information was successfully deleted.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_basic_information
      @basic_information = BasicInformation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def basic_information_params
      params.require(:basic_information).permit(
        :first_name,
        :last_name,
        :email,
        :bp,
        :height,
        :weight,
        :dob
      )
    end
end

app/controllers/bladder_managements_controller.rb
class BladderManagementsController < ApplicationController
  before_action :set_bladder_management, only: [:show, :destroy]

  # GET /basic_informations
  # GET /basic_informations.json
  def index
    @bladder_managements = BladderManagement.all
  end


  # GET /basic_informations/1
  # GET /basic_informations/1.json
  def show
  end

  # POST /basic_informations
  # POST /basic_informations.json
  def create
    @bladder_management = BasicInformation.new(bladder_management_params)

    respond_to do |format|
      if @bladder_management.save
        format.html { redirect_to @bladder_management, notice: 'Bladder management information was successfully created.' }
      else
        format.html { render :index }
      end
    end
  end

  # PATCH/PUT /basic_informations/1
  # PATCH/PUT /basic_informations/1.json
  def update
  end

  # DELETE /basic_informations/1
  # DELETE /basic_informations/1.json
  def destroy
    @bladder_management.destroy
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path, notice: 'Bladder management information was successfully deleted.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bladder_management
      @bladder_management = BladderManagement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bladder_management_params
      params.require(:bladder_management).permit(
        :response,
        :indwelling_catheter,
        :condom_catheter,
        :suprapubic_catheter,
        :intermittent_catheterization_urethra,
        :intermittent_catheterization_stoma,
        :ileal_conduit,
        :other,
        :other_details
      )
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/saage_forms_controller.rb
class SaageFormsController < ApplicationController
  before_action :set_saage_form, only: [:update, :destroy]  
  # GET /saage_forms
  # GET /saage_forms.json

  # GET /saage_forms/new
  def new
    @saage_form = SaageForm.new
    @saage_form.build_basic_information
    @saage_form.build_bladder_management
  end

  # POST /saage_forms
  # POST /saage_forms.json
  def create
    @saage_form = SaageForm.new(saage_form_params)
    respond_to do |format|
      if @saage_form.save!      
        format.html { redirect_to my_care_plan_path, notice: 'SAAGE information was successfully created.' }
      else
        render :new
      end
    end
  end

  # PATCH/PUT /saage_forms/1
  # PATCH/PUT /saage_forms/1.json
  def update
  end

  # DELETE /saage_forms/1
  # DELETE /saage_forms/1.json
  def destroy
    @saage_form.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_saage_form
      @saage_form = SaageForm.find(params[:id])
      # fill params
    end

    # Only allow a list of trusted parameters through.
    def saage_form_params
      params.require(:saage_form).permit(
        basic_information_attributes: [
          :id,
          :first_name,
          :last_name,
          :email,
          :bp,
          :height,
          :weight,
          :dob
        ],
        bladder_management_attributes: [
          :response,
          :indwelling_catheter,
          :condom_catheter,
          :suprapubic_catheter,
          :intermittent_catheterization_urethra,
          :intermittent_catheterization_stoma,
          :ileal_conduit,
          :other,
          :other_details
        ]
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/basic_informations/_form.html.erb
<div>
  <h5>Basic Information</h5>

  <%= form.fields_for basic_information do |bi| %>
    <div class="subsection">
      <div class="row">
        <h5 class="subsection-title">About Me</h5>
      </div>

      <div class="form-row">
        <div class="form-group col-md-6">
          <%= bi.label :first_name %>
          <%= bi.text_field :first_name, class: "form-control" %>
        </div>
        <div class="form-group col-md-6">
          <%= bi.label :last_name %>
          <%= bi.text_field :last_name, class: "form-control" %>
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-6">
          <%= bi.label :email %>
          <%= bi.email_field :email, class: "form-control" %>
        </div>
        <div class="form-group col-md-6">
          <%= bi.label "Typical Blood Pressure" %>
          <%= bi.text_field :bp, class: "form-control" %>
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-6">
          <%= bi.label :height %>
          <%= bi.text_field :height, class: "form-control" %>
        </div>
        <div class="form-group col-md-6">
          <%= bi.label :weight %>
          <%= bi.text_field :weight, class: "form-control" %>
        </div>
      </div>

      <div class="form-row">
        <div class="input-group mb-3">
          <%= bi.text_field :dob, class: "form-control datepicker", placeholder: "Date of birth", autocomplete: "off" %>
        </div>
      </div>

    </div>

    <div class="actions" hidden>
      <%= bi.submit %>
    </div>
  <% end %>
</div>

<%= javascript_pack_tag 'basic_informations/form' %>

app/views/basic_informations/index.html.erb
<div class="row title">
  <div class="col-md-12">
    <h1>Basic Informations</h1>
  </div>
</div>

<div class="row title">
  <div class="col-md-2">F Name
  </div>
  <div class="col-md-2">L Name
  </div>
  <div class="col-md-2">Email
  </div>
  <div class="col-md-1">BP
  </div>
  <div class="col-md-1">Height
  </div>
  <div class="col-md-1">Weight
  </div>  
  <div class="col-md-1">DOB
  </div>    
  <div class="col-md-2">Actions
  </div>      
</div>

<% @basic_informations.each do |basic_information| %>
  <div class="row">
    <div class="col-md-2"><%= basic_information.first_name %>
    </div>
    <div class="col-md-2"><%= basic_information.last_name %>
    </div>
    <div class="col-md-2"><%= basic_information.email %>
    </div>
    <div class="col-md-1"><%= basic_information.bp %>
    </div>
    <div class="col-md-1"><%= basic_information.height %>
    </div>
    <div class="col-md-1"><%= basic_information.weight %>
    </div>  
    <div class="col-md-1"><%= basic_information.dob %>
    </div>    
    <div class="col-md-2"><%= link_to 'Show', basic_information %> | <%= link_to 'Destroy', basic_information, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>      
  </div>
<% end %>

app/views/basic_informations/show.html.erb
<div class="row title">
  <div class="col-md-12">
    <p>
      <strong>First name:</strong>
      <%= @basic_information.first_name %>
    </p>

    <p>
      <strong>Last name:</strong>
      <%= @basic_information.last_name %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @basic_information.email %>
    </p>

    <p>
      <strong>Bp:</strong>
      <%= @basic_information.bp %>
    </p>

    <p>
      <strong>Height:</strong>
      <%= @basic_information.height %>
    </p>

    <p>
      <strong>Weight:</strong>
      <%= @basic_information.weight %>
    </p>

    <p>
      <strong>Dob:</strong>
      <%= @basic_information.dob %>
    </p>

    <%= link_to 'Back', basic_informations_path %>

  </div>
</div>

app/views/bladder_managements/_form.html.erb
<div>
  <h5>Bladder Management</h5>

  <%= form.fields_for bladder_management do |bladder| %>

    <p>Spinal cord injury typically affects the way your urinary system works, requiring a management routine that may involve a variety of techniques and supplies.</p>

    <div class="subsection">
      <div class="row">
        <h5 class="subsection-title">Bladder Routine Details</h5>
      </div>


      <div class="row">
        <p class="col-12">Does your spinal cord injury affect your urinary function?</p>
      </div>
      <%= bladder.hidden_field :response, value: "unsure", id: "bladder-response" %>
      <input type="radio" name="bladder_question" value="yes"> Yes
      <input type="radio" name="bladder_question" value="no"> No
      <input type="radio" name="bladder_question" value="unsure" checked> I'm not sure

      <div id="bladder-answer" class="row">

        <div id="bladder-routine" class="col-12" style="display: none;">

          <div class="form-row">
            <p>What does your bladder management routine typically involve?</p>
          </div>

          <div class="form-check">
            <%= bladder.check_box :indwelling_catheter, class: "form-check-input", id: "bladder-checkIndwellingCatheter" %>
            <%= bladder.label "Indwelling catheter and collection bag", class: "form-check-label", for: "bladder-checkIndwellingCatheter" %>
          </div>

          <div class="form-check">
            <%= bladder.check_box :condom_catheter, class: "form-check-input", id: "bladder-checkCondomCatheter" %>
            <%= bladder.label "Condom (external) catheter and collection bag", class: "form-check-label", for: "bladder-checkCondomCatheter" %>
          </div>

          <div class="form-check">
            <%= bladder.check_box :suprapubic_catheter, class: "form-check-input", id: "bladder-checkSuprapubicCatheter" %>
            <%= bladder.label "Suprapubic catheter and collection bag", class: "form-check-label", for: "bladder-checkSuprapubicCatheter" %>
          </div>

          <div class="form-check">
            <%= bladder.check_box :intermittent_catheterization_urethra, class: "form-check-input", id: "bladder-checkIntermittentCatheterizationUrethra" %>
            <%= bladder.label "Intermittent catheterization (in and out) through my urethra", class: "form-check-label", for: "bladder-checkIntermittentCatheterizationUrethra" %>
          </div>

          <div class="form-check">
            <%= bladder.check_box :intermittent_catheterization_stoma, class: "form-check-input", id: "bladder-checkIntermittentCatheterizationStoma" %>
            <%= bladder.label "Intermittent catheterization (in and out) through an abdominal stoma (mitrofanoff)", class: "form-check-label", for: "bladder-checkIntermittentCatheterizationStoma" %>
          </div>

          <div class="form-check">
            <%= bladder.check_box :ileal_conduit, class: "form-check-input", id: "bladder-checkIlealConduit" %>
            <%= bladder.label "Ileal conduit/urostomy and collection bag", class: "form-check-label", for: "bladder-checkIlealConduit" %>
          </div>

          <div class="form-check">
            <%= bladder.check_box :other, class: "form-check-input", id: "bladder-checkOther" %>
            <%= bladder.label "Other", class: "form-check-label", for: "bladder-checkOther" %>
          </div>

          <div id="bladder-other-details" style="display: none;">
            <p>If you answered "other," you can add details here:</p>
            <%= bladder.text_field :other_details, class: "form-control" %>
          </div>

        </div>

        <div id="bladder-details">
          <p>Do you want to provide more information?</p>
          <%= bladder.text_field :details, class: "form-control" %>
        </div>

      </div>

    </div>


    <div class="actions" hidden>
      <%= bladder.submit %>
    </div>
  <% end %>
</div>

<%= javascript_pack_tag 'bladder_managements/form' %>

app/views/bladder_managements/index.html.erb
<div class="row title">
  <div class="col-md-12">
    <h1>Bladder Managements</h1>
  </div>
</div>

<div class="row title">
  <div class="col-md-1">Response
  </div>
  <div class="col-md-1">Ind. Cath.
  </div>
  <div class="col-md-1">C. Cath.
  </div>
  <div class="col-md-1">S. Cath.
  </div>
  <div class="col-md-1">Int. Cath: Urethra
  </div>
  <div class="col-md-1">Int. Cath: Stoma
  </div>  
  <div class="col-md-1">Il. Conduit
  </div>    
  <div class="col-md-1">Other
  </div>      
  <div class="col-md-2">Details
  </div>    
  <div class="col-md-2">Actions
  </div>      
</div>

<% @bladder_managements.each do |bladder_management| %>
  <div class="row">
    <div class="col-md-1"><%= bladder_management.response %>
    </div>
    <div class="col-md-1"><%= bladder_management.indwelling_catheter %>
    </div>
    <div class="col-md-1"><%= bladder_management.condom_catheter %>
    </div>
    <div class="col-md-1"><%= bladder_management.suprapubic_catheter %>
    </div>
    <div class="col-md-1"><%= bladder_management.intermittent_catheterization_urethra %>
    </div>
    <div class="col-md-1"><%= bladder_management.intermittent_catheterization_stoma %>
    </div>
    <div class="col-md-1"><%= bladder_management.ileal_conduit %>
    </div>
    <div class="col-md-1"><%= bladder_management.other %>
    </div>  
    <div class="col-md-2"><%= bladder_management.other_details %>
    </div>    
    <div class="col-md-2"><%= link_to 'Show', bladder_management %> | <%= link_to 'Destroy', bladder_management, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>      
  </div>
<% end %>

app/views/bladder_managements/show.html.erb
<div class="row title">
  <div class="col-md-12">
    <p>
      <strong>Response:</strong>
      <%= @bladder_management.response %>
    </p>

    <p>
      <strong>Indwelling catheter:</strong>
      <%= @bladder_management.indwelling_catheter %>
    </p>

    <p>
      <strong>Condom catheter:</strong>
      <%= @bladder_management.condom_catheter %>
    </p>

    <p>
      <strong>Suprapubic catheter:</strong>
      <%= @bladder_management.suprapubic_catheter %>
    </p>

    <p>
      <strong>Intermittent catheterization urethra:</strong>
      <%= @bladder_management.intermittent_catheterization_urethra %>
    </p>

    <p>
      <strong>Intermittent catheterization stoma:</strong>
      <%= @bladder_management.intermittent_catheterization_stoma %>
    </p>

    <p>
      <strong>Ileal conduit:</strong>
      <%= @bladder_management.ileal_conduit %>
    </p>

    <p>
      <strong>Other:</strong>
      <%= @bladder_management.other %>
    </p>

    <p>
      <strong>Other details:</strong>
      <%= @bladder_management.other_details %>
    </p>

    <%= link_to 'Back', bladder_managements_path %>
  </div>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-success" role="alert">
	<div class="d-flex justify-content-center">
		<% flash.each do |key, value| %>
		      <p><%= value %></p>
		<% end %>
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
  <%= link_to image_tag("SAAGElogo.png", id: 'logo', class: "navbar-brand"), root_path, id: "header-logo" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item"><%= link_to "My care plan", my_care_plan_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "How to use", how_to_use_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spinal Cord Injury: My Self-Care Information</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/le-frog/jquery-ui.min.css' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/alerts' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <h1>About</h1>
  <p>This project was initiated in response to the COVID-19 pandemic, to support people living with SCI who need to be admitted to hospital.</p>
  <h2>What You Get</h2>
  <div class="col-12">
    <%= image_tag('SAAGEInfographic1.png', id:'infographic-1') %>
  </div>
  <h2>Team</h2>
  <p>Developed by the SCI+U team, based in the University of Toronto's Physical Therapy department. Funding provided by the Praxis Spinal Cord Institute.</p>
  <h2>Methods</h2>
  <p>Developed during the summer of 2020 using an agile process with user feedback ...</p>
  <h2>Open Source</h2>
  <p>All intellectual properties ...</p>
  <p>Merry xMas!!!</p>
 
</div>

app/views/pages/how_to_use.html.erb
<div class="container">
  <h1>How To Use</h1>
  <p>You can create a personal care plan with information about your self-management routines. This may be useful if you are admitted to hospital.</p>
  <h4>Enter your information</h4>
  <p>Enter information that is relevant to your situation using the care plan form.</p>
  <h4>Share with your care team</h4>
  <p>Share your information with health care providers and members of your care team.</p>
  <p><%= image_tag('SAAGEInfographic2.png', id:'infographic-2') %></p> 
  <h4>Delete your information</h4>
  <p>Permanently delete your information.</p>
  <h4>Security and Privacy</h4>
  <p>

    </p>
  </div>

app/views/pages/my_care_plan.html.erb
<div class="container">
  <h1 class="row col-12">My Health Care Plan</h1>
  <h5>Enter information about your self-management routines and other needs</h5>

  <div class="row">
    <%= link_to "Enter My Plan", new_saage_form_path, class: "btn btn-success col-12 col-centered" %>
  </div>
  <div class="space">

  </div>
  <h2>Share Information</h2>
  <h5>Share your information with health care providers and members of your care team</h5>
  <div class="row">
    <%= link_to "Share My Plan", "", class: "btn btn-success col-12 col-centered disabled" %>
  </div>

  <div class="space">

  </div>
  <h2>Delete Information</h2>
  <h5>Permanently delete your information or account</h5>
  <div class="row">
    <%= link_to "Delete", "", class: "btn btn-danger col-12 col-centered" %>
  </div>
</div>

app/views/saage_forms/_form.html.erb
<%= form_for saage_form do |form| %>
  <ul class="pagination">
    <li class="page-item active" aria-current="page" id="page-1"><a class="page-link" href="javascript:void(0)">1</a></li>
    <li class="page-item" id="page-2"><a class="page-link" href="javascript:void(0)">2</a></li>
    <!--
    <li class="page-item" id="page-3"><a class="page-link" href="javascript:void(0)">3</a></li>
    <li class="page-item" id="page-4"><a class="page-link" href="javascript:void(0)">4</a></li>
    <li class="page-item" id="page-5"><a class="page-link" href="javascript:void(0)">5</a></li>
    <li class="page-item" id="page-6"><a class="page-link" href="javascript:void(0)">6</a></li>
    <li class="page-item" id="page-7"><a class="page-link" href="javascript:void(0)">7</a></li>
    <li class="page-item" id="page-8"><a class="page-link" href="javascript:void(0)">8</a></li>
    -->
  </ul>

  <div class="sections" id="section-page-1"><%= render 'basic_informations/form', form: form, basic_information: :basic_information %></div>
  <div class="sections" id="section-page-2"><%= render 'bladder_managements/form', form: form, bladder_management: :bladder_management %></div>

  <div><%= form.submit "Submit Form", class: "actions btn btn-primary" %></div>
<% end %>

<%= javascript_pack_tag 'saage_forms/form' %>

app/views/saage_forms/new.html.erb
<div class="container">

  <div class="row col-12">
    <h3 id="title">Spinal Cord Injury:</h3>
  </div>
  <div class="row col-12">
    <h3 id="subtitle">My Self-Care Information</h3>
  </div>

  <%= render 'form', saage_form: @saage_form %>
</div>

<div class="d-flex justify-content-center">
	<button type="button" class="btn btn-primary">
		<%= link_to 'Back', my_care_plan_path %>
	</button>
</div>